"""chunk has user_id

Revision ID: 4e6288182e4c
Revises: b79d9cfc00ec
Create Date: 2023-08-05 18:43:15.281336

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4e6288182e4c'
down_revision = 'b79d9cfc00ec'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chunks', sa.Column('user_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'chunks', 'profiles', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'chunks', type_='foreignkey')
    op.drop_column('chunks', 'user_id')
    # ### end Alembic commands ###
